name: Build and Deploy LiteLLM to AWS ECR

on:
  push:
    branches:
      - production
      - staging
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 'Build and push image for production branch'
        if: github.ref == 'refs/heads/production'
        run: |
          docker buildx build --build-arg LITELLM_BUILD_IMAGE=cgr.dev/chainguard/python:latest-dev \
                              --build-arg LITELLM_RUNTIME_IMAGE=cgr.dev/chainguard/python:latest-dev \
                              -t ${{ steps.login-ecr.outputs.registry }}/eai/production:litellm-latest \
                              -t ${{ steps.login-ecr.outputs.registry }}/eai/production:litellm-${{ github.sha }} \
                              --push .

      - name: 'Build and push image for staging branch'
        if: github.ref == 'refs/heads/staging'
        run: |
          docker buildx build --build-arg LITELLM_BUILD_IMAGE=cgr.dev/chainguard/python:latest-dev \
                              --build-arg LITELLM_RUNTIME_IMAGE=cgr.dev/chainguard/python:latest-dev \
                              -t ${{ steps.login-ecr.outputs.registry }}/eai/staging:litellm-latest \
                              -t ${{ steps.login-ecr.outputs.registry }}/eai/staging:litellm-${{ github.sha }} \
                              --push .

      - name: 'Notification on success'
        if: success()
        run: |
          echo "✅ LiteLLM Docker image successfully built and pushed to ECR"
          echo "Branch: ${{ github.ref_name }}"
          echo "Commit: ${{ github.sha }}"
          echo "Repository: eai/${{ github.ref == 'refs/heads/production' && 'production' || 'staging' }}"
          echo "Tags: litellm-latest, litellm-${{ github.sha }}"

      - name: 'Notification on failure'
        if: failure()
        run: |
          echo "❌ LiteLLM Docker build and push failed"
          echo "Branch: ${{ github.ref_name }}"
          echo "Commit: ${{ github.sha }}"
          exit 1 